version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=newworld_db
      - DB_SSLMODE=disable
      - JWT_SECRET=your_jwt_secret_key_here_make_it_long_and_secure
      - JWT_ACCESS_TOKEN_EXPIRY=3600
      - JWT_REFRESH_TOKEN_EXPIRY=604800
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_email@gmail.com
      - SMTP_PASSWORD=your_app_password
      - EMAIL_FROM=your_email@gmail.com
      - APP_NAME=NewWorld Project
      - APP_URL=http://localhost:8080
      - FRONTEND_URL=http://localhost:3000
      - BCRYPT_COST=12
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW=900
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=newworld_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 